export { default as ElegantFloralTemplate } from './ElegantFloralTemplate'
export { default as ModernMinimalTemplate } from './ModernMinimalTemplate'
export { default as RusticKraftTemplate } from './RusticKraftTemplate'
export { default as PlayfulPastelTemplate } from './PlayfulPastelTemplate'
export { default as ParisianNoirTemplate } from './ParisianNoirTemplate'
export { default as BentoGridTemplate } from './BentoGridTemplate'
