const blogPosts = [
  {
    title: 'Creating Standard Operating Procedures for Your Bakery',
    description: 'Complete guide to creating bakery SOPs with free downloadable templates. Learn why SOPs matter, how to write them, train your team, and ensure consistency in your bakery operations.',
    slug: 'bakery-sop-guide',
    date: 'February 6, 2025',
    readTime: '24 min read',
    category: 'Operations Guide',
    featured: true,
  },
  {
    title: 'Home Bakery Success Rates: What Makes Businesses Thrive',
    description: 'Discover the real success rates of home bakeries, why 60% succeed while 40% fail, and the proven factors that make bakery businesses thrive. Data-driven insights and actionable strategies.',
    slug: 'home-bakery-success-rates',
    date: 'February 6, 2025',
    readTime: '22 min read',
    category: 'Industry Insights',
    featured: true,
  },
  {
    title: 'What Customers Really Pay for Cakes: 2025 Price Survey',
    description: 'Comprehensive 2025 cake pricing survey reveals what customers actually pay for wedding cakes, birthday cakes, cupcakes, and custom designs. Real market data to help you price confidently.',
    slug: 'cake-price-survey-2025',
    date: 'February 6, 2025',
    readTime: '20 min read',
    category: 'Pricing Guide',
    featured: true,
  },
  {
    title: 'How to Create a Bakery Email List (And What to Send)',
    description: 'Learn how to build an email list for your bakery from scratch. Includes free tools, lead magnet ideas, email templates, and proven strategies to get repeat customers.',
    slug: 'bakery-email-list-guide',
    date: 'February 6, 2025',
    readTime: '19 min read',
    category: 'Email Marketing',
    featured: true,
  },
  {
    title: 'Bakery Branding on a Budget: Complete DIY Guide for Under $100',
    description: 'Create a professional bakery brand without breaking the bank. Learn DIY logo design, social media branding, packaging ideas, and free tools to build your bakery identity.',
    slug: 'bakery-branding-on-budget',
    date: 'February 5, 2025',
    readTime: '18 min read',
    category: 'Branding & Marketing',
    featured: true,
  },
  {
    title: 'How to Create a Bakery Menu That Sells',
    description: 'Complete guide to creating a profitable bakery menu. Learn product selection, pricing psychology, menu descriptions, design tips, and common mistakes to avoid.',
    slug: 'bakery-menu-guide',
    date: 'February 6, 2025',
    readTime: '17 min read',
    category: 'Menu Strategy',
    featured: true,
  },
  {
    title: 'Home Bakery Business Plan Template (Free Download)',
    description: 'Complete business plan template for home bakeries. Interactive form with 8 sections covering executive summary, financials, marketing, and goals. Download instantly.',
    slug: 'business-plan-template',
    date: 'February 5, 2025',
    readTime: '20 min read',
    category: 'Business Planning',
    featured: true,
  },
  {
    title: 'How to Start a Home Bakery with $500 or Less',
    description: 'Complete guide to starting a profitable home bakery on a shoestring budget. Includes budget breakdown, equipment list, legal requirements, and free marketing strategies.',
    slug: 'start-home-bakery-budget',
    date: 'February 4, 2025',
    readTime: '18 min read',
    category: 'Getting Started',
    featured: true,
  },
  {
    title: 'Break-Even Analysis for Bakers: When Do You Start Making Money?',
    description: 'Learn how to calculate your break-even point and know exactly when your bakery becomes profitable. Includes real examples, formulas, and growth planning strategies.',
    slug: 'break-even-analysis',
    date: 'February 3, 2025',
    readTime: '16 min read',
    category: 'Business Strategy',
    featured: true,
  },
  {
    title: 'How to Calculate Your True Hourly Rate as a Baker',
    description: 'Most bakers drastically overestimate their hourly rate. Learn how to track ALL your time—baking, admin, delivery—and calculate what you\'re really making per hour.',
    slug: 'true-hourly-rate',
    date: 'February 2, 2025',
    readTime: '15 min read',
    category: 'Labor & Pricing',
    featured: true,
  },
  {
    title: 'Cupcake Pricing Guide: $2 vs $5 vs $8 - What\'s Right for You?',
    description: 'Discover which cupcake pricing tier is right for your bakery. Compare budget, mid-tier, and premium strategies with real cost breakdowns and profit analysis.',
    slug: 'cupcake-pricing-guide',
    date: 'February 1, 2025',
    readTime: '17 min read',
    category: 'Pricing Strategy',
    featured: true,
  },
  {
    title: 'The 3 Biggest Pricing Mistakes Home Bakers Make (And How to Fix Them)',
    description: 'Discover the 3 critical pricing mistakes costing home bakers thousands every year. Learn how to fix undercharging, missing overhead, and undervaluing your time.',
    slug: 'pricing-mistakes',
    date: 'January 31, 2025',
    readTime: '16 min read',
    category: 'Pricing Strategy',
    featured: true,
  },
  {
    title: 'Why You\'re Losing Money on Every Cake (And Don\'t Know It)',
    description: 'Most home bakers lose money on every cake they sell. Discover the 7 hidden costs killing your profits and learn how to fix your pricing without losing customers.',
    slug: 'losing-money-on-cakes',
    date: 'January 30, 2025',
    readTime: '18 min read',
    category: 'Pricing & Profitability',
    featured: true,
  },
  {
    title: 'How to Calculate Recipe Cost: Complete Guide for Bakers (2025)',
    description: 'Learn the exact formula to calculate recipe costs including ingredients, labor, overhead, and profit margins. Includes free calculator and real examples.',
    slug: 'how-to-calculate-recipe-cost',
    date: 'January 15, 2025',
    readTime: '12 min read',
    category: 'Recipe Costing',
    featured: true,
  },
  {
    title: 'Cake Pricing Formula: How to Price Cakes for Profit (2025)',
    description: 'Learn the exact formula to price cakes profitably. Includes complexity multipliers, tier pricing, delivery fees, and real examples with free calculator.',
    slug: 'how-to-price-cakes',
    date: 'January 15, 2025',
    readTime: '14 min read',
    category: 'Cake Pricing',
    featured: false,
  },
  {
    title: 'How to Start a Home Bakery Business: Complete Guide (2025)',
    description: 'Complete guide to starting a profitable home bakery. Learn legal requirements, equipment needs, pricing strategies, marketing tactics, and systems to succeed.',
    slug: 'how-to-start-home-bakery',
    date: 'January 15, 2025',
    readTime: '18 min read',
    category: 'Home Bakery',
    featured: false,
  },
  {
    title: 'How to Price Cupcakes: Complete Pricing Guide for Bakers (2025)',
    description: 'Learn how to price cupcakes profitably with step-by-step formulas, real examples, specialty pricing, and common mistakes to avoid. Free calculator included.',
    slug: 'how-to-price-cupcakes',
    date: 'January 15, 2025',
    readTime: '15 min read',
    category: 'Cupcake Pricing',
    featured: false,
  },
  {
    title: 'Recipe Cost Calculator: Excel vs Software (Which is Better?)',
    description: 'Compare Excel spreadsheets vs dedicated recipe cost calculator software. Learn the pros, cons, real cost analysis, and when to switch.',
    slug: 'recipe-cost-calculator-comparison',
    date: 'January 20, 2025',
    readTime: '14 min read',
    category: 'Tools & Software',
    featured: true,
  },
  {
    title: '10 Best Recipe Cost Calculators for Home Bakers (2025)',
    description: 'Research-based review of 10 recipe cost calculators. Compare features, pricing, pros & cons of BakeProfit, meez, CakeCost, and more.',
    slug: 'best-recipe-calculators',
    date: 'January 22, 2025',
    readTime: '18 min read',
    category: 'Tools Review',
    featured: true,
  },
  {
    title: 'How to Track Ingredient Costs for Your Home Bakery (2025 Guide)',
    description: 'Learn how to track ingredient costs, handle price fluctuations, reduce waste, and boost bakery profits. Includes 5 tracking methods and automation tips.',
    slug: 'track-ingredient-costs',
    date: 'January 28, 2025',
    readTime: '12 min read',
    category: 'Ingredient Tracking',
    featured: false,
  },
  {
    title: 'Bakery Profit Margins: What\'s Normal and How to Improve Yours (2025)',
    description: 'Learn what profit margins are normal for bakeries, how to calculate yours, and 10 proven strategies to improve profitability. Includes industry benchmarks and real examples.',
    slug: 'bakery-profit-margins',
    date: 'January 28, 2025',
    readTime: '12 min read',
    category: 'Profit Margins',
    featured: false,
  }
]


export default blogPosts
